apiVersion: v1
kind: Pod
metadata:
  name: monitor
  namespace: ros-test
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Never
  containers:
    - name: ros2-monitor
      image: back1ash/ros2-monitor:0.0.1
      imagePullPolicy: Always
      env:
        - name: RMW_IMPLEMENTATION
          value: rmw_fastrtps_cpp
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
      securityContext:
        capabilities:
          add: ["SYS_PTRACE"]
