apiVersion: v1
kind: Pod
metadata:
  name: rt-totaltest
  namespace: ros-test
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Never
  containers:
    - name: ros2-rttest
      image: back1ash/ros2-rttest:0.1.0
      imagePullPolicy: Always
      env:
        - name: CMD
          value: all
        - name: CYCLICTEST_ARGS
          value: "--threads=1 -l 10000 -i 500 --json=/output/cyclictest_result.json"
        - name: PISTRESS_ARGS
          value: "-g 8 -i 100000"
        - name: SIGNALTEST_ARGS
          value: "-p 30 -l 300 --json=/output/signaltest_result.json"
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_NICE
            - SYS_RESOURCE
      volumeMounts:
        - name: output
          mountPath: /output
  volumes:
    - name: output
      emptyDir: {}
